workflow: 
  rules:
    -if: $CI_COMMIT_TAG
     when: never
    -if: $CI_COMMIT_BRANCH == 'master'

varibles:
  IMAGE_OPENJDK_GRADLE: gradle:7.1.0-jdk11

stages:
  -clean
  -build
  -test
  -build-image
  -publish-image
  -deploy

clean:
  image: $IMAGE_OPENJDK_GRADLE
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/gradlew clean

coverage-test:
  image: $IMAGE_OPENJDK_GRADLE
  stage: test
  needs: 
    -job: unit-test
  submit:
    -echo: "Running coverage tests..."

build-image:
  stage: build-image
  script:
    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY/kanimstv/api:$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY/kanimstv/api:latest .
  
publish-image:
  stage: publish-image
  script:
    - echo "Publishing Docker Image..."
    - docker login -u kanimstv -p $KANIMSTV_CONTAINER_REGISTRY_TOKEN
  $CI_REGISTRY
    - docker push $CI_REGISTRY/kanimstv/api:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/kanimstv/api:latest

